### ISSUE TITLE
TailwindCSS and htmldjango

### ISSUE THREAD

**Issue by rob32** [lcfd/NaryaVim#21]
Great config! Thanks for sharing <3

Just a small question: 
In templates, tailwind snipptes/autocompletion are not working or?

My tailwind-config are also not in root... lspinfo shows the tailwind-lsp is running 🤔

**Comment by rob32** [comment]
Hey Luca, thanks for the quick reply <3

`LspInfo` shows that tailwindcss is active for the buffer and also the filetype is set correctly as htmldjango.

I have now also tried it with your lsp-config, but still no success regarding tailwind snippets/autocomplete.

Even if the _tailwind.config.js_ is located in the root directory

.. that really drives me crazy ^^

**Comment by lcfd** [comment]
Ok, so we need to go deeper.

Have you tried to use this [config](https://github.com/lcfd/NaryaVim/blob/f761d30e8fb7cbb70c28c73a7c658611a2e91dab/lua/plugins/snippets.lua#L29)? It's a tricky thing.

**Comment by rob32** [comment]
Hey, thank you for taking the time and effort to help me! Very appreciate it.

I have now completely loaded your config and only made small adjustments (keybindings/options). I like it very much!

Unfortunately tailwindcss snippets/autocomplete still do not work with filetype `htmldjango`.

According to `Lspinfo` Tailwindcss is atached to the buffer:

![htmldjango-lsp-tailwindcss](https://github.com/lcfd/NaryaVim/assets/49953458/12627e38-fc0c-4434-8a07-f3813ef00756)

I noticed that you don't have `htmldjango` in your [treesiter-config](https://github.com/lcfd/NaryaVim/blob/f761d30e8fb7cbb70c28c73a7c658611a2e91dab/lua/plugins/treesitter.lua#L25)

I have added that. Could this be the reason?

**Comment by lcfd** [comment]
I'm glad you are liking it! 
I'm putting quite some effort to keep it updated 💪

Have you tried to open the folder where the `tailwind.config.js` is located?

Run `nvim .` → open the HTML file → try use `class="<TYPE HERE>"`.

**Comment by rob32** [comment]
HeyHey,
thank you very much!

I was able to find the error 🙏

In the repo where i always tested it was a "data" folder/volume (docker).
In the end it was a problem with permissions...

Have a nice weekend :rocket:

**Comment by lcfd** [comment]
I'm glad you solved!
Thank you for reporting it.
It's a strange case, but I think not that uncommon.

Have a nice weekend you too 😁
